version: '3.8'

services:
  db:
    build: ./mysql/
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    healthcheck:
      test: "mysql -e \"SHOW DATABASES;\""
      interval: 10s
      timeout: 60s
      retries: 3
  
  backend:
    depends_on:
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /home/savio/dockerzao-main/compose/bind_mount_compose/flask:/app
    networks:
      - dockercompose

networks:
  dockercompose: {}